### ISSUE TITLE
demos produce asdf-standard 1.1.0 files that use `core/asdf-1.1.0` instead of `core/asdf-1.0.0`

### ISSUE THREAD

**Issue by braingram** [eschnett/asdf-cxx#6]
Thanks again for putting together this package. I've been having fun testing this against the python asdf implementation and encountered one issue (that I think is an easy fix).

The demo files are produced with a comment noting asdf-standard 1.1.0 (here are the first few lines of `demo.asdf`):
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.1.0
# This is an ASDF file <https://asdf-standard.readthedocs.io/>
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
---
!core/asdf-1.1.0
asdf/library: !core/software-1.0.0
```
However, the `core/asdf-1.1.0` tag doesn't exist in the 1.1.0 version of the standard:
https://asdf-standard.readthedocs.io/en/1.0.3/generated/asdf-format.org/core/core-1.1.0.html
This produces a warning in asdf 3.0 when the file is opened:
```
AsdfConversionWarning: tag:stsci.edu:asdf/core/asdf-1.1.0 is not recognized, converting to raw Python data structure
```
If I manually edit the `ASDF_STANDARD` comment to `1.2.0` I no longer see the warning as the 1.1.0 tag exists in the 1.2.0 standard:
https://asdf-standard.readthedocs.io/en/1.0.3/generated/asdf-format.org/core/core-1.2.0.html

I think this can be fixed by changing this to `1.2.0`:
https://github.com/eschnett/asdf-cxx/blob/ac74dcf3c51c9912bef9731ba2b82507830fa869/src/io.cxx#L13

**Comment by eschnett** [comment]
Thanks for the pointer! I was trying to debug this this morning and couldn't figure out what was wrong.
